version: 2.1

executors:
  docker-machine-executor:
    machine:
      image: ubuntu-2004:202101-01  # Uses a full virtual machine

jobs:
  build-frontend:
    executor: docker-machine-executor  # Reference the executor here
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build frontend Docker image
          command: |
            docker build -t hoangson00/udagram-frontend ./udagram-frontend

      - run:
          name: Login to DockerHub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin

      - run:
          name: Push frontend image to DockerHub
          command: |
            docker push hoangson00/udagram-frontend

  build-backend:
    executor: docker-machine-executor  # Reference the executor here
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build backend Docker images
          command: |
            docker build -t hoangson00/udagram-api-feed ./udagram-api-feed
            docker build -t hoangson00/udagram-api-user ./udagram-api-user

      - run:
          name: Login to DockerHub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin

      - run:
          name: Push backend images to DockerHub
          command: |
            docker push hoangson00/udagram-api-feed
            docker push hoangson00/udagram-api-user

  build-reverseproxy:
    executor: docker-machine-executor  # Reference the executor here
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build reverseproxy Docker image
          command: |
            docker build -t hoangson00/udagram-reverseproxy ./udagram-reverseproxy

      - run:
          name: Login to DockerHub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin

      - run:
          name: Push reverseproxy image to DockerHub
          command: |
            docker push hoangson00/udagram-reverseproxy

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-frontend
      - build-backend
      - build-reverseproxy
