version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:16
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_TOKEN

jobs:
  build-frontend:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Login to DockerHub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - run:
          name: Build frontend Docker image
          command: docker build -t udagram-frontend ./udagram-frontend
      - run:
          name: Tag frontend Docker image
          command: docker tag udagram-frontend hoangson00/udagram-frontend:v1
      - run:
          name: Push frontend image to DockerHub
          command: docker push hoangson00/udagram-frontend:v1

  build-backend-feed:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Login to DockerHub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - run:
          name: Build backend-feed Docker image
          command: docker build -t udagram-api-feed ./udagram-api-feed
      - run:
          name: Tag backend-feed Docker image
          command: docker tag udagram-api-feed hoangson00/udagram-api-feed:v1
      - run:
          name: Push backend-feed image to DockerHub
          command: docker push hoangson00/udagram-api-feed:v1

  build-backend-user:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Login to DockerHub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - run:
          name: Build backend-user Docker image
          command: docker build -t udagram-api-user ./udagram-api-user
      - run:
          name: Tag backend-user Docker image
          command: docker tag udagram-api-user hoangson00/udagram-api-user:v1
      - run:
          name: Push backend-user image to DockerHub
          command: docker push hoangson00/udagram-api-user:v1

  build-reverseproxy:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Login to DockerHub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
      - run:
          name: Build reverseproxy Docker image
          command: docker build -t udagram-reverseproxy ./udagram-reverseproxy
      - run:
          name: Tag reverseproxy Docker image
          command: docker tag udagram-reverseproxy hoangson00/udagram-reverseproxy:v1
      - run:
          name: Push reverseproxy image to DockerHub
          command: docker push hoangson00/udagram-reverseproxy:v1

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-frontend
      - build-backend-feed
      - build-backend-user
      - build-reverseproxy
